### Get All Item

GET http://localhost:8080/handytools

### Get Item By ID
GET http://localhost:8080/handytools/1

### Get InValid Item By ID
GET http://localhost:8080/handytools/10

### Get Item Location
GET http://localhost:8080/handytools/where/1

### Get Item Location With Invalid ID
GET http://localhost:8080/handytools/where/10

### Get Loan History 
GET http://localhost:8080/handytools/history/3

### Get Loan History with Invalid Id
GET http://localhost:8080/handytools/history/10

### Add New Item
POST http://localhost:8080/handytools/add
Content-Type: application/json

{
    "toolDetail": "cutter",
    "ownerName": "napat",
    "location": "S2"
}

### Borrow an item
PUT http://localhost:8080/handytools/borrow/1
Content-Type: application/json

{
  "borrowerName": "save",
  "use_location": "R6"
}

### Borrow an item that are being borrowed
PUT http://localhost:8080/handytools/borrow/2
Content-Type: application/json

{
  "borrowerName": "save",
  "use_location": "R3"
}

### Return Item
PUT http://localhost:8080/handytools/return/2
Content-Type: application/json

{
  "location": "S3"
}

### Return The item that has not been borrowed
PUT http://localhost:8080/handytools/return/3
Content-Type: application/json

{
  "location": "S3"
}

### Delete an item
DELETE http://localhost:8080/handytools/delete/1