### 

GET http://localhost:8080/handytools


### Add New Item
POST http://localhost:8080/handytools/add
Content-Type: application/json

{
    "toolDetail": "cutter",
    "ownerName": "napat",
    "location": "S2"
}

###
POST http://localhost:8080/handytools
Content-Type: application/json

{
    "toolDetail": "drill",
    "ownerName": "kt",
    "locationName": "hanging at the barn's wall",
    "borrowed": false,
    "borrowedName": null
}

###
GET http://localhost:8080/handytools/99

###
PUT http://localhost:8080/handytools/1
Content-Type: application/json

{
    "toolDetail": "new tool name for #1",
    "ownerName": "kt",
    "locationName": "in the box under the desk",
    "borrowed": false,
    "borrowedName": null
}

###
DELETE http://localhost:8080/handytools/5